apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: hrzn-acme
spec:
  acme:
    email: webmaster@hrzn.studio
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: hrzn-acme-prod-account-key
    dns01:
      providers:
      - name: hrzn-cloudflare
        cloudflare:
          email: hello@chipwolf.uk
          apiKeySecretRef:
            name: cloudflare-api-key
            key: api-key
